### ISSUE TITLE
cargo vendor: failed to sync

### ISSUE THREAD

**Issue by fiersik** [MalpenZibo/ashell#25]
How can I fix this error when using cargo vendor?

```shell
error: failed to sync

Caused by:
  found duplicate version of package `clipboard_wayland v0.2.2` vendored from two sources:

        source 1: registry `crates-io`
        source 2: https://github.com/pop-os/window_clipboard.git?tag=pop-dnd-6#8a816d8f
```

This is necessary to build without internet access during compilation, in my case, to build the package into the Sisyphus repository for ALT Linux

**Comment by MalpenZibo** [comment]
The problem is not easy to resolve see: https://github.com/rust-lang/cargo/issues/10310

The project uses the iced.rs library and [my fork of iced](https://github.com/MalpenZibo/iced_sctk) from pop_os that both use clipboard_wayland (one from crate and one from pop_os repo).

To resolve the issue I have to change the dependency from clipboard_wayland (pop_os repo version) to the crate one but to do that I had to change the codebase. Otherwise, I already planned an alternative solution https://github.com/MalpenZibo/ashell/issues/24.

Currently, I do not have a workaround.

**Comment by MalpenZibo** [comment]
@fiersik Can you try with the latest commit on the main branch? 
In case I will proceed with a new release

**Comment by fiersik** [comment]
I really managed to build an rpm package! I consider it fixed
