### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by nonetrix** [MalpenZibo/ashell#4]
As it is currently, it seems ashell will just spawn on whatever monitor is focused. Would be great if multiple monitor support was added, also I like to use a extension to give each monitor their own workspaces like DWM and that might need some work https://github.com/Duckonaut/split-monitor-workspaces

**Comment by nonetrix** [comment]
Also a `--help` flag would be nice, sorry for making so many issues just found a lot that I think should be added

**Comment by MalpenZibo** [comment]
This feature would be a very nice addition. Still, right now it isn't easy to implement because https://github.com/MalpenZibo/iced_sctk (that's the library to use the Wayland layer surface protocol from the iced toolkit) doesn't have a way to specify a target monitor. 
I have wait until the system76 team implements this feature for their cosmic DE.

**Comment by MalpenZibo** [comment]
It's been a while but I'm almost ready to merge this feature in the main branch https://github.com/MalpenZibo/ashell/pull/43
