### ISSUE TITLE
No battery display

### ISSUE THREAD

**Issue by pnotequalnp** [MalpenZibo/ashell#76]
Was using an old commit for some time, updated to master, no longer displays the battery level.

It does give some errors but they don't seem very relevant to this issue.
```
INFO [ashell::config] Reading config file
WARN [wgpu_hal::gles::adapter] Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
ERROR [ashell::services::bluetooth] Failed to initialize bluetooth service: No such file or directory (os error 2)
ERROR [ashell::services::bluetooth] Bluetooth service error
ERROR [ashell::services::upower] Failed to initialize upower service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower.PowerProfiles was not provided by any .service files
```
Unless the power profiles service is causing all power-related things to fail.
I'm on NixOS, not sure what additional information would be relevant.

**Comment by MalpenZibo** [comment]
The problem seems that without the org.freedesktop.UPower.PowerProfiles dbus protocol the entire service fail to initialize (so even the battery).

A temporary workaround could be install something that makes that protocol work on your system but I should decouple the two things to really fix the issue.

I will try to resolve as soon as I can. It shouldn't be so complicated

**Comment by MalpenZibo** [comment]
you could try with this branch https://github.com/MalpenZibo/ashell/pull/77

**Comment by pnotequalnp** [comment]
> you could try with this branch #77

Works! Thanks for the quick resolution.

**Comment by Sean1708** [comment]
Just FYI, this has started happening again. I don't know whether it's the same cause, but it is the same symptoms (battery indicators don't work unless the upower interface can be activated).

**Comment by clotodex** [comment]
Could you describe your exact system setup please?

**Comment by Sean1708** [comment]
@clotodex Sorry for the noise, but I've realised it was an issue on my end. UPower itself was not enabled (rather than the `UPower.PowerProfiles` interface), and obviously battery functionality is going to need UPower. I guess you could make the argument that `ashell` should fall back to `/sys/` if UPower isn't enabled, but I don't think that's a worthwhile change.

**Comment by clotodex** [comment]
Nice thanks for the input
And yeah debating a lot of this on the network side so migjt revisit this when we start implementing fallbacks there
Closing for now :)
